import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import { App } from "./App";

// The static table generated by tools/build-register.py stays in the page for readers without
// JavaScript; once the application mounts it is hidden so the data is not shown twice.
export function mount(doc: Document): boolean {
  const host = doc.getElementById("register-app");
  if (host === null) {
    return false;
  }
  const source = host.dataset["source"] ?? "/tools/register.json";
  const fallback = doc.getElementById("register-static");
  if (fallback !== null) {
    fallback.hidden = true;
  }
  createRoot(host).render(
    <StrictMode>
      <App source={source} />
    </StrictMode>,
  );
  return true;
}
