import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import { App, type LoadState } from "./App";

// The static table generated by tools/build-register.py stays in the page for readers without
// JavaScript and whenever the register cannot be loaded; once the application has the data it
// is hidden so the table is not shown twice.
export function mount(doc: Document): boolean {
  const host = doc.getElementById("register-app");
  if (host === null) {
    return false;
  }
  const source = host.dataset["source"] ?? "/tools/register.json";
  const fallback = doc.getElementById("register-static");
  const onLoad = (state: LoadState) => {
    if (fallback !== null) {
      fallback.hidden = state === "ready";
    }
  };
  createRoot(host).render(
    <StrictMode>
      <App source={source} onLoad={onLoad} />
    </StrictMode>,
  );
  return true;
}
