// Shapes of tools/register.json, generated by tools/build-register.py from the tool pages.

export type Level = "green" | "amber" | "red" | "none" | "ungraded";

export interface Grade {
  mark: string;
  level: Level;
}

export interface NoteSegment {
  text: string;
  href?: string;
}

export type Kind = "tool" | "toolchain";

export interface Tool {
  slug: string;
  name: string;
  page: string;
  language: string;
  kind: Kind;
  readiness: Grade;
  detector: Grade;
  toolchain: Grade;
  project: Grade;
  notes: NoteSegment[];
  checked: string;
}

export interface Register {
  languages: string[];
  tools: Tool[];
}

export const GRADE_COLUMNS = [
  "readiness",
  "detector",
  "toolchain",
  "project",
] as const;

export type GradeColumn = (typeof GRADE_COLUMNS)[number];

export type SortKey =
  "default" | "name" | "language" | "kind" | GradeColumn | "checked";

export type SortDirection = "asc" | "desc";

export interface Sort {
  key: SortKey;
  direction: SortDirection;
}

export interface Filters {
  query: string;
  languages: string[];
  kinds: Kind[];
  grades: Record<GradeColumn, Level[]>;
  sort: Sort;
}
